Revisao dos exercicios resolvidos
kassiano/FIAP-2020 pull request #2
Opened 2020-03-05 20:17 UTC by plpcout

Revisao dos exercicios resolvidos

2020-03-05 20:28 UTC, plpcout commented
sem validacoes a principio

2020-03-07 19:46 UTC, kassiano requested changes
Fiz alguns comentários de coisas que poderiam melhorar. Mas ta tudo certo

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex04.kt
> +        println("Digite o $i"+"ª nota:")
Utilize sempre $ para concatenações

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex06.kt
> +fun areaCirculo(n:Double):Double{
Essa função poderia ser uma extension de `Double`

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex07.kt
> +fun areaQuadrado(n:Double):Double{
Essa tbm poderia ser extension

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex12.kt
> +    }
Aqui poderia retornar direto do IF sem precisar dessa variavel `resp`, assim:
```
return if (n > 0) {
        "Positivo"
    } else if (n < 0) {
        "Negativo"
    } else {
         "Zero"
    }
```

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex13.kt
> +fun sexoTipo(n: Char) {
Aqui, o sexo poderia chegar em String mesmo. E a comparação de Strings pode ser feita com `==` sem problemas

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex14.kt
> +}
Aqui vc poderia ter criado uma lista de vogais e verificado se a letra esta na lista:
```
val vogais = listOf("a", "e", "i", "o", "u")

if(voagais.contains(letra)) {
   //é vogal
}

```

acho que a lógica ficaria mais clara, tem que considerar maiuculas e minusculas tbm

2020-03-07 19:46 UTC, kassiano commented on Aula03/Ex16.kt
> +}
Essa função poderia ficar numa única linha:
```
fun suspeitar(n: Int): Boolean = if(n == 1) true else false
```

2020-03-07 22:46 UTC, closed without merging